name: Terraform Dev (LocalStack)

on:
  workflow_dispatch:

jobs:
  terraform-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Start LocalStack container
        run: |
          docker compose -f terraform/dev/docker-compose.yml up -d

      - name: Wait for LocalStack
        run: |
          echo "Waiting for LocalStack services..."
          until curl -s http://localhost:4566/_localstack/health | jq -e '.services.s3 == "available"' > /dev/null; do
            echo "LocalStack not ready yet..."
            sleep 2
          done
          echo "LocalStack is ready!"

      - name: Terraform Init
        run: terraform -chdir=terraform/dev init -input=false

      - name: Terraform Plan
        run: terraform -chdir=terraform/dev plan -out=tfplan

      - name: Terraform Apply
        run: terraform -chdir=terraform/dev apply -auto-approve -input=false

      - name: Terraform Destroy
        if: always()
        run: terraform -chdir=terraform/dev destroy -auto-approve -input=false
